/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        gradlePluginPortal() 
        mavenCentral()
    }
}

rootProject.name = "java_coding_test"
gradle.extra["GIT_DIR"] = "../.git"