name = "coding_test"
uuid = "97138895-4aa0-4db5-a334-7c126a3f2e3a"
authors = ["kimdeokyoung <dudejrss@naver.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
Glob = "1.3.1"
JuliaFormatter = "2.1.6"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
