name = "coding_test"
uuid = "97138895-4aa0-4db5-a334-7c126a3f2e3a"
authors = ["kimdeokyoung <dudejrss@naver.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
