/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "2.1.20"
    id("com.diffplug.spotless") version "7.0.2"
}

repositories {
    gradlePluginPortal() 
    mavenCentral()
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit)
    testImplementation(libs.junit.junit)
}

group = "com.example."
version = "1.0-SNAPSHOT"
description = "kotlin"


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

kotlin {
    jvmToolchain(17)
}

spotless {
    kotlin {
        target("src/**/*.kt") 
        ktfmt().googleStyle().configure {
          it.setMaxWidth(80)
          it.setBlockIndent(4)
          it.setContinuationIndent(4)
          it.setRemoveUnusedImports(false)
          it.setManageTrailingCommas(false)
        }
    }
}