/*
 * This file was generated by the Gradle 'init' task.
 */

pluginManagement {
    repositories {
        gradlePluginPortal() 
        mavenCentral()
    }
}

rootProject.name = "kotlin_coding_test"
